/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BillingItemApprovalLevelsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BillingItemApprovalLevelsApiTests
    {
        private BillingItemApprovalLevelsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BillingItemApprovalLevelsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillingItemApprovalLevelsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BillingItemApprovalLevelsApi
            //Assert.IsInstanceOfType(typeof(BillingItemApprovalLevelsApi), instance, "instance is a BillingItemApprovalLevelsApi");
        }


        /// <summary>
        /// Test BillingItemApprovalLevelsCreateEntity
        /// </summary>
        [Test]
        public void BillingItemApprovalLevelsCreateEntityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BillingItemApprovalLevelModel restModelInput = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.BillingItemApprovalLevelsCreateEntity(restModelInput, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<OperationResultModel> (response, "response is OperationResultModel");
        }

        /// <summary>
        /// Test BillingItemApprovalLevelsQuery
        /// </summary>
        [Test]
        public void BillingItemApprovalLevelsQueryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //QueryModel queryModel = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.BillingItemApprovalLevelsQuery(queryModel, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<QueryActionResultBillingItemApprovalLevelModelBillingItemApprovalLevel> (response, "response is QueryActionResultBillingItemApprovalLevelModelBillingItemApprovalLevel");
        }

        /// <summary>
        /// Test BillingItemApprovalLevelsQueryCount
        /// </summary>
        [Test]
        public void BillingItemApprovalLevelsQueryCountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //QueryModel queryModel = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.BillingItemApprovalLevelsQueryCount(queryModel, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<QueryCountResultModel> (response, "response is QueryCountResultModel");
        }

        /// <summary>
        /// Test BillingItemApprovalLevelsQueryEntityInformation
        /// </summary>
        [Test]
        public void BillingItemApprovalLevelsQueryEntityInformationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.BillingItemApprovalLevelsQueryEntityInformation(apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<EntityInformationResultModel> (response, "response is EntityInformationResultModel");
        }

        /// <summary>
        /// Test BillingItemApprovalLevelsQueryFieldDefinitions
        /// </summary>
        [Test]
        public void BillingItemApprovalLevelsQueryFieldDefinitionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.BillingItemApprovalLevelsQueryFieldDefinitions(apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<FieldInformationResultModel> (response, "response is FieldInformationResultModel");
        }

        /// <summary>
        /// Test BillingItemApprovalLevelsQueryItem
        /// </summary>
        [Test]
        public void BillingItemApprovalLevelsQueryItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.BillingItemApprovalLevelsQueryItem(id, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<ItemQueryResultModelBillingItemApprovalLevelModelBillingItemApprovalLevel> (response, "response is ItemQueryResultModelBillingItemApprovalLevelModelBillingItemApprovalLevel");
        }

        /// <summary>
        /// Test BillingItemApprovalLevelsQueryUserDefinedFieldDefinitions
        /// </summary>
        [Test]
        public void BillingItemApprovalLevelsQueryUserDefinedFieldDefinitionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.BillingItemApprovalLevelsQueryUserDefinedFieldDefinitions(apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<UserDefinedFieldInformationResultModel> (response, "response is UserDefinedFieldInformationResultModel");
        }

        /// <summary>
        /// Test BillingItemApprovalLevelsUrlParameterQuery
        /// </summary>
        [Test]
        public void BillingItemApprovalLevelsUrlParameterQueryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string search = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.BillingItemApprovalLevelsUrlParameterQuery(search, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<QueryActionResultBillingItemApprovalLevelModelBillingItemApprovalLevel> (response, "response is QueryActionResultBillingItemApprovalLevelModelBillingItemApprovalLevel");
        }

        /// <summary>
        /// Test BillingItemApprovalLevelsUrlParameterQueryCount
        /// </summary>
        [Test]
        public void BillingItemApprovalLevelsUrlParameterQueryCountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string search = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.BillingItemApprovalLevelsUrlParameterQueryCount(search, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<QueryCountResultModel> (response, "response is QueryCountResultModel");
        }

    }

}
