/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InventoryItemSerialNumbersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class InventoryItemSerialNumbersApiTests
    {
        private InventoryItemSerialNumbersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new InventoryItemSerialNumbersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InventoryItemSerialNumbersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' InventoryItemSerialNumbersApi
            //Assert.IsInstanceOfType(typeof(InventoryItemSerialNumbersApi), instance, "instance is a InventoryItemSerialNumbersApi");
        }


        /// <summary>
        /// Test InventoryItemSerialNumbersQuery
        /// </summary>
        [Test]
        public void InventoryItemSerialNumbersQueryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //QueryModel queryModel = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.InventoryItemSerialNumbersQuery(queryModel, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<QueryActionResultInventoryItemSerialNumberModelInventoryItemSerialNumber> (response, "response is QueryActionResultInventoryItemSerialNumberModelInventoryItemSerialNumber");
        }

        /// <summary>
        /// Test InventoryItemSerialNumbersQueryCount
        /// </summary>
        [Test]
        public void InventoryItemSerialNumbersQueryCountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //QueryModel queryModel = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.InventoryItemSerialNumbersQueryCount(queryModel, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<QueryCountResultModel> (response, "response is QueryCountResultModel");
        }

        /// <summary>
        /// Test InventoryItemSerialNumbersQueryEntityInformation
        /// </summary>
        [Test]
        public void InventoryItemSerialNumbersQueryEntityInformationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.InventoryItemSerialNumbersQueryEntityInformation(apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<EntityInformationResultModel> (response, "response is EntityInformationResultModel");
        }

        /// <summary>
        /// Test InventoryItemSerialNumbersQueryFieldDefinitions
        /// </summary>
        [Test]
        public void InventoryItemSerialNumbersQueryFieldDefinitionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.InventoryItemSerialNumbersQueryFieldDefinitions(apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<FieldInformationResultModel> (response, "response is FieldInformationResultModel");
        }

        /// <summary>
        /// Test InventoryItemSerialNumbersQueryItem
        /// </summary>
        [Test]
        public void InventoryItemSerialNumbersQueryItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.InventoryItemSerialNumbersQueryItem(id, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<ItemQueryResultModelInventoryItemSerialNumberModelInventoryItemSerialNumber> (response, "response is ItemQueryResultModelInventoryItemSerialNumberModelInventoryItemSerialNumber");
        }

        /// <summary>
        /// Test InventoryItemSerialNumbersQueryUserDefinedFieldDefinitions
        /// </summary>
        [Test]
        public void InventoryItemSerialNumbersQueryUserDefinedFieldDefinitionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.InventoryItemSerialNumbersQueryUserDefinedFieldDefinitions(apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<UserDefinedFieldInformationResultModel> (response, "response is UserDefinedFieldInformationResultModel");
        }

        /// <summary>
        /// Test InventoryItemSerialNumbersUrlParameterQuery
        /// </summary>
        [Test]
        public void InventoryItemSerialNumbersUrlParameterQueryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string search = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.InventoryItemSerialNumbersUrlParameterQuery(search, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<QueryActionResultInventoryItemSerialNumberModelInventoryItemSerialNumber> (response, "response is QueryActionResultInventoryItemSerialNumberModelInventoryItemSerialNumber");
        }

        /// <summary>
        /// Test InventoryItemSerialNumbersUrlParameterQueryCount
        /// </summary>
        [Test]
        public void InventoryItemSerialNumbersUrlParameterQueryCountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string search = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.InventoryItemSerialNumbersUrlParameterQueryCount(search, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<QueryCountResultModel> (response, "response is QueryCountResultModel");
        }

    }

}
