/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PurchaseOrderItemReceivingChildApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PurchaseOrderItemReceivingChildApiTests
    {
        private PurchaseOrderItemReceivingChildApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PurchaseOrderItemReceivingChildApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PurchaseOrderItemReceivingChildApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PurchaseOrderItemReceivingChildApi
            //Assert.IsInstanceOfType(typeof(PurchaseOrderItemReceivingChildApi), instance, "instance is a PurchaseOrderItemReceivingChildApi");
        }


        /// <summary>
        /// Test PurchaseOrderItemReceivingChildCreateEntity
        /// </summary>
        [Test]
        public void PurchaseOrderItemReceivingChildCreateEntityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? parentId = null;
            //PurchaseOrderItemReceivingModel restModelInput = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.PurchaseOrderItemReceivingChildCreateEntity(parentId, restModelInput, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<OperationResultModel> (response, "response is OperationResultModel");
        }

        /// <summary>
        /// Test PurchaseOrderItemReceivingChildQuery
        /// </summary>
        [Test]
        public void PurchaseOrderItemReceivingChildQueryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? parentId = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.PurchaseOrderItemReceivingChildQuery(parentId, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<QueryActionResultPurchaseOrderItemReceivingModelPurchaseOrderReceive> (response, "response is QueryActionResultPurchaseOrderItemReceivingModelPurchaseOrderReceive");
        }

        /// <summary>
        /// Test PurchaseOrderItemReceivingChildQueryEntityInformation
        /// </summary>
        [Test]
        public void PurchaseOrderItemReceivingChildQueryEntityInformationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string parentId = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.PurchaseOrderItemReceivingChildQueryEntityInformation(parentId, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<EntityInformationResultModel> (response, "response is EntityInformationResultModel");
        }

        /// <summary>
        /// Test PurchaseOrderItemReceivingChildQueryFieldDefinitions
        /// </summary>
        [Test]
        public void PurchaseOrderItemReceivingChildQueryFieldDefinitionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string parentId = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.PurchaseOrderItemReceivingChildQueryFieldDefinitions(parentId, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<FieldInformationResultModel> (response, "response is FieldInformationResultModel");
        }

        /// <summary>
        /// Test PurchaseOrderItemReceivingChildQueryItem
        /// </summary>
        [Test]
        public void PurchaseOrderItemReceivingChildQueryItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? parentId = null;
            //long? id = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.PurchaseOrderItemReceivingChildQueryItem(parentId, id, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<ItemQueryResultModelPurchaseOrderItemReceivingModelPurchaseOrderReceive> (response, "response is ItemQueryResultModelPurchaseOrderItemReceivingModelPurchaseOrderReceive");
        }

        /// <summary>
        /// Test PurchaseOrderItemReceivingChildQueryUserDefinedFieldDefinitions
        /// </summary>
        [Test]
        public void PurchaseOrderItemReceivingChildQueryUserDefinedFieldDefinitionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string parentId = null;
            //string apiIntegrationCode = null;
            //string userName = null;
            //string secret = null;
            //string impersonationResourceId = null;
            //var response = instance.PurchaseOrderItemReceivingChildQueryUserDefinedFieldDefinitions(parentId, apiIntegrationCode, userName, secret, impersonationResourceId);
            //Assert.IsInstanceOf<UserDefinedFieldInformationResultModel> (response, "response is UserDefinedFieldInformationResultModel");
        }

    }

}
