/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AppointmentModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppointmentModelTests
    {
        // TODO uncomment below to declare an instance variable for AppointmentModel
        //private AppointmentModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppointmentModel
            //instance = new AppointmentModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppointmentModel
        /// </summary>
        [Test]
        public void AppointmentModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppointmentModel
            //Assert.IsInstanceOfType<AppointmentModel> (instance, "variable 'instance' is a AppointmentModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreateDateTime'
        /// </summary>
        [Test]
        public void CreateDateTimeTest()
        {
            // TODO unit test for the property 'CreateDateTime'
        }
        /// <summary>
        /// Test the property 'CreatorResourceID'
        /// </summary>
        [Test]
        public void CreatorResourceIDTest()
        {
            // TODO unit test for the property 'CreatorResourceID'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'EndDateTime'
        /// </summary>
        [Test]
        public void EndDateTimeTest()
        {
            // TODO unit test for the property 'EndDateTime'
        }
        /// <summary>
        /// Test the property 'ResourceID'
        /// </summary>
        [Test]
        public void ResourceIDTest()
        {
            // TODO unit test for the property 'ResourceID'
        }
        /// <summary>
        /// Test the property 'StartDateTime'
        /// </summary>
        [Test]
        public void StartDateTimeTest()
        {
            // TODO unit test for the property 'StartDateTime'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'UpdateDateTime'
        /// </summary>
        [Test]
        public void UpdateDateTimeTest()
        {
            // TODO unit test for the property 'UpdateDateTime'
        }
        /// <summary>
        /// Test the property 'UserDefinedFields'
        /// </summary>
        [Test]
        public void UserDefinedFieldsTest()
        {
            // TODO unit test for the property 'UserDefinedFields'
        }

    }

}
