/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BillingItemModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BillingItemModelTests
    {
        // TODO uncomment below to declare an instance variable for BillingItemModel
        //private BillingItemModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BillingItemModel
            //instance = new BillingItemModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillingItemModel
        /// </summary>
        [Test]
        public void BillingItemModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BillingItemModel
            //Assert.IsInstanceOfType<BillingItemModel> (instance, "variable 'instance' is a BillingItemModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AccountManagerWhenApprovedID'
        /// </summary>
        [Test]
        public void AccountManagerWhenApprovedIDTest()
        {
            // TODO unit test for the property 'AccountManagerWhenApprovedID'
        }
        /// <summary>
        /// Test the property 'BillingCodeID'
        /// </summary>
        [Test]
        public void BillingCodeIDTest()
        {
            // TODO unit test for the property 'BillingCodeID'
        }
        /// <summary>
        /// Test the property 'BillingItemType'
        /// </summary>
        [Test]
        public void BillingItemTypeTest()
        {
            // TODO unit test for the property 'BillingItemType'
        }
        /// <summary>
        /// Test the property 'CompanyID'
        /// </summary>
        [Test]
        public void CompanyIDTest()
        {
            // TODO unit test for the property 'CompanyID'
        }
        /// <summary>
        /// Test the property 'ConfigurationItemID'
        /// </summary>
        [Test]
        public void ConfigurationItemIDTest()
        {
            // TODO unit test for the property 'ConfigurationItemID'
        }
        /// <summary>
        /// Test the property 'ContractChargeID'
        /// </summary>
        [Test]
        public void ContractChargeIDTest()
        {
            // TODO unit test for the property 'ContractChargeID'
        }
        /// <summary>
        /// Test the property 'ContractID'
        /// </summary>
        [Test]
        public void ContractIDTest()
        {
            // TODO unit test for the property 'ContractID'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ExpenseItemID'
        /// </summary>
        [Test]
        public void ExpenseItemIDTest()
        {
            // TODO unit test for the property 'ExpenseItemID'
        }
        /// <summary>
        /// Test the property 'ExtendedPrice'
        /// </summary>
        [Test]
        public void ExtendedPriceTest()
        {
            // TODO unit test for the property 'ExtendedPrice'
        }
        /// <summary>
        /// Test the property 'InternalCurrencyExtendedPrice'
        /// </summary>
        [Test]
        public void InternalCurrencyExtendedPriceTest()
        {
            // TODO unit test for the property 'InternalCurrencyExtendedPrice'
        }
        /// <summary>
        /// Test the property 'InternalCurrencyRate'
        /// </summary>
        [Test]
        public void InternalCurrencyRateTest()
        {
            // TODO unit test for the property 'InternalCurrencyRate'
        }
        /// <summary>
        /// Test the property 'InternalCurrencyTaxDollars'
        /// </summary>
        [Test]
        public void InternalCurrencyTaxDollarsTest()
        {
            // TODO unit test for the property 'InternalCurrencyTaxDollars'
        }
        /// <summary>
        /// Test the property 'InternalCurrencyTotalAmount'
        /// </summary>
        [Test]
        public void InternalCurrencyTotalAmountTest()
        {
            // TODO unit test for the property 'InternalCurrencyTotalAmount'
        }
        /// <summary>
        /// Test the property 'InvoiceID'
        /// </summary>
        [Test]
        public void InvoiceIDTest()
        {
            // TODO unit test for the property 'InvoiceID'
        }
        /// <summary>
        /// Test the property 'ItemApproverID'
        /// </summary>
        [Test]
        public void ItemApproverIDTest()
        {
            // TODO unit test for the property 'ItemApproverID'
        }
        /// <summary>
        /// Test the property 'ItemDate'
        /// </summary>
        [Test]
        public void ItemDateTest()
        {
            // TODO unit test for the property 'ItemDate'
        }
        /// <summary>
        /// Test the property 'ItemName'
        /// </summary>
        [Test]
        public void ItemNameTest()
        {
            // TODO unit test for the property 'ItemName'
        }
        /// <summary>
        /// Test the property 'LineItemFullDescription'
        /// </summary>
        [Test]
        public void LineItemFullDescriptionTest()
        {
            // TODO unit test for the property 'LineItemFullDescription'
        }
        /// <summary>
        /// Test the property 'LineItemGroupDescription'
        /// </summary>
        [Test]
        public void LineItemGroupDescriptionTest()
        {
            // TODO unit test for the property 'LineItemGroupDescription'
        }
        /// <summary>
        /// Test the property 'MilestoneID'
        /// </summary>
        [Test]
        public void MilestoneIDTest()
        {
            // TODO unit test for the property 'MilestoneID'
        }
        /// <summary>
        /// Test the property 'NonBillable'
        /// </summary>
        [Test]
        public void NonBillableTest()
        {
            // TODO unit test for the property 'NonBillable'
        }
        /// <summary>
        /// Test the property 'OrganizationalLevelAssociationID'
        /// </summary>
        [Test]
        public void OrganizationalLevelAssociationIDTest()
        {
            // TODO unit test for the property 'OrganizationalLevelAssociationID'
        }
        /// <summary>
        /// Test the property 'OurCost'
        /// </summary>
        [Test]
        public void OurCostTest()
        {
            // TODO unit test for the property 'OurCost'
        }
        /// <summary>
        /// Test the property 'PostedDate'
        /// </summary>
        [Test]
        public void PostedDateTest()
        {
            // TODO unit test for the property 'PostedDate'
        }
        /// <summary>
        /// Test the property 'PostedOnTime'
        /// </summary>
        [Test]
        public void PostedOnTimeTest()
        {
            // TODO unit test for the property 'PostedOnTime'
        }
        /// <summary>
        /// Test the property 'ProjectChargeID'
        /// </summary>
        [Test]
        public void ProjectChargeIDTest()
        {
            // TODO unit test for the property 'ProjectChargeID'
        }
        /// <summary>
        /// Test the property 'ProjectID'
        /// </summary>
        [Test]
        public void ProjectIDTest()
        {
            // TODO unit test for the property 'ProjectID'
        }
        /// <summary>
        /// Test the property 'PurchaseOrderNumber'
        /// </summary>
        [Test]
        public void PurchaseOrderNumberTest()
        {
            // TODO unit test for the property 'PurchaseOrderNumber'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Rate'
        /// </summary>
        [Test]
        public void RateTest()
        {
            // TODO unit test for the property 'Rate'
        }
        /// <summary>
        /// Test the property 'RoleID'
        /// </summary>
        [Test]
        public void RoleIDTest()
        {
            // TODO unit test for the property 'RoleID'
        }
        /// <summary>
        /// Test the property 'ServiceBundleID'
        /// </summary>
        [Test]
        public void ServiceBundleIDTest()
        {
            // TODO unit test for the property 'ServiceBundleID'
        }
        /// <summary>
        /// Test the property 'ServiceID'
        /// </summary>
        [Test]
        public void ServiceIDTest()
        {
            // TODO unit test for the property 'ServiceID'
        }
        /// <summary>
        /// Test the property 'SortOrderID'
        /// </summary>
        [Test]
        public void SortOrderIDTest()
        {
            // TODO unit test for the property 'SortOrderID'
        }
        /// <summary>
        /// Test the property 'SubType'
        /// </summary>
        [Test]
        public void SubTypeTest()
        {
            // TODO unit test for the property 'SubType'
        }
        /// <summary>
        /// Test the property 'TaskID'
        /// </summary>
        [Test]
        public void TaskIDTest()
        {
            // TODO unit test for the property 'TaskID'
        }
        /// <summary>
        /// Test the property 'TaxDollars'
        /// </summary>
        [Test]
        public void TaxDollarsTest()
        {
            // TODO unit test for the property 'TaxDollars'
        }
        /// <summary>
        /// Test the property 'TicketChargeID'
        /// </summary>
        [Test]
        public void TicketChargeIDTest()
        {
            // TODO unit test for the property 'TicketChargeID'
        }
        /// <summary>
        /// Test the property 'TicketID'
        /// </summary>
        [Test]
        public void TicketIDTest()
        {
            // TODO unit test for the property 'TicketID'
        }
        /// <summary>
        /// Test the property 'TimeEntryID'
        /// </summary>
        [Test]
        public void TimeEntryIDTest()
        {
            // TODO unit test for the property 'TimeEntryID'
        }
        /// <summary>
        /// Test the property 'TotalAmount'
        /// </summary>
        [Test]
        public void TotalAmountTest()
        {
            // TODO unit test for the property 'TotalAmount'
        }
        /// <summary>
        /// Test the property 'VendorID'
        /// </summary>
        [Test]
        public void VendorIDTest()
        {
            // TODO unit test for the property 'VendorID'
        }
        /// <summary>
        /// Test the property 'WebServiceDate'
        /// </summary>
        [Test]
        public void WebServiceDateTest()
        {
            // TODO unit test for the property 'WebServiceDate'
        }
        /// <summary>
        /// Test the property 'UserDefinedFields'
        /// </summary>
        [Test]
        public void UserDefinedFieldsTest()
        {
            // TODO unit test for the property 'UserDefinedFields'
        }

    }

}
