/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ComanagedAssociationModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ComanagedAssociationModelTests
    {
        // TODO uncomment below to declare an instance variable for ComanagedAssociationModel
        //private ComanagedAssociationModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ComanagedAssociationModel
            //instance = new ComanagedAssociationModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ComanagedAssociationModel
        /// </summary>
        [Test]
        public void ComanagedAssociationModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ComanagedAssociationModel
            //Assert.IsInstanceOfType<ComanagedAssociationModel> (instance, "variable 'instance' is a ComanagedAssociationModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CompanyID'
        /// </summary>
        [Test]
        public void CompanyIDTest()
        {
            // TODO unit test for the property 'CompanyID'
        }
        /// <summary>
        /// Test the property 'ResourceID'
        /// </summary>
        [Test]
        public void ResourceIDTest()
        {
            // TODO unit test for the property 'ResourceID'
        }
        /// <summary>
        /// Test the property 'UserDefinedFields'
        /// </summary>
        [Test]
        public void UserDefinedFieldsTest()
        {
            // TODO unit test for the property 'UserDefinedFields'
        }

    }

}
