/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CompanyWebhookFieldModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CompanyWebhookFieldModelTests
    {
        // TODO uncomment below to declare an instance variable for CompanyWebhookFieldModel
        //private CompanyWebhookFieldModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CompanyWebhookFieldModel
            //instance = new CompanyWebhookFieldModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompanyWebhookFieldModel
        /// </summary>
        [Test]
        public void CompanyWebhookFieldModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CompanyWebhookFieldModel
            //Assert.IsInstanceOfType<CompanyWebhookFieldModel> (instance, "variable 'instance' is a CompanyWebhookFieldModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FieldID'
        /// </summary>
        [Test]
        public void FieldIDTest()
        {
            // TODO unit test for the property 'FieldID'
        }
        /// <summary>
        /// Test the property 'IsDisplayAlwaysField'
        /// </summary>
        [Test]
        public void IsDisplayAlwaysFieldTest()
        {
            // TODO unit test for the property 'IsDisplayAlwaysField'
        }
        /// <summary>
        /// Test the property 'IsSubscribedField'
        /// </summary>
        [Test]
        public void IsSubscribedFieldTest()
        {
            // TODO unit test for the property 'IsSubscribedField'
        }
        /// <summary>
        /// Test the property 'WebhookID'
        /// </summary>
        [Test]
        public void WebhookIDTest()
        {
            // TODO unit test for the property 'WebhookID'
        }
        /// <summary>
        /// Test the property 'SoapParentPropertyId'
        /// </summary>
        [Test]
        public void SoapParentPropertyIdTest()
        {
            // TODO unit test for the property 'SoapParentPropertyId'
        }
        /// <summary>
        /// Test the property 'UserDefinedFields'
        /// </summary>
        [Test]
        public void UserDefinedFieldsTest()
        {
            // TODO unit test for the property 'UserDefinedFields'
        }

    }

}
