/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ContractRateModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContractRateModelTests
    {
        // TODO uncomment below to declare an instance variable for ContractRateModel
        //private ContractRateModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContractRateModel
            //instance = new ContractRateModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContractRateModel
        /// </summary>
        [Test]
        public void ContractRateModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ContractRateModel
            //Assert.IsInstanceOfType<ContractRateModel> (instance, "variable 'instance' is a ContractRateModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ContractHourlyRate'
        /// </summary>
        [Test]
        public void ContractHourlyRateTest()
        {
            // TODO unit test for the property 'ContractHourlyRate'
        }
        /// <summary>
        /// Test the property 'ContractID'
        /// </summary>
        [Test]
        public void ContractIDTest()
        {
            // TODO unit test for the property 'ContractID'
        }
        /// <summary>
        /// Test the property 'InternalCurrencyContractHourlyRate'
        /// </summary>
        [Test]
        public void InternalCurrencyContractHourlyRateTest()
        {
            // TODO unit test for the property 'InternalCurrencyContractHourlyRate'
        }
        /// <summary>
        /// Test the property 'RoleID'
        /// </summary>
        [Test]
        public void RoleIDTest()
        {
            // TODO unit test for the property 'RoleID'
        }
        /// <summary>
        /// Test the property 'SoapParentPropertyId'
        /// </summary>
        [Test]
        public void SoapParentPropertyIdTest()
        {
            // TODO unit test for the property 'SoapParentPropertyId'
        }
        /// <summary>
        /// Test the property 'UserDefinedFields'
        /// </summary>
        [Test]
        public void UserDefinedFieldsTest()
        {
            // TODO unit test for the property 'UserDefinedFields'
        }

    }

}
