/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Expression
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExpressionTests
    {
        // TODO uncomment below to declare an instance variable for Expression
        //private Expression instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Expression
            //instance = new Expression();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Expression
        /// </summary>
        [Test]
        public void ExpressionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Expression
            //Assert.IsInstanceOfType<Expression> (instance, "variable 'instance' is a Expression");
        }


        /// <summary>
        /// Test the property 'NodeType'
        /// </summary>
        [Test]
        public void NodeTypeTest()
        {
            // TODO unit test for the property 'NodeType'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'CanReduce'
        /// </summary>
        [Test]
        public void CanReduceTest()
        {
            // TODO unit test for the property 'CanReduce'
        }

    }

}
