/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ItemQueryResultModelConfigurationItemWebhookModelInstalledProductWebhook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemQueryResultModelConfigurationItemWebhookModelInstalledProductWebhookTests
    {
        // TODO uncomment below to declare an instance variable for ItemQueryResultModelConfigurationItemWebhookModelInstalledProductWebhook
        //private ItemQueryResultModelConfigurationItemWebhookModelInstalledProductWebhook instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ItemQueryResultModelConfigurationItemWebhookModelInstalledProductWebhook
            //instance = new ItemQueryResultModelConfigurationItemWebhookModelInstalledProductWebhook();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemQueryResultModelConfigurationItemWebhookModelInstalledProductWebhook
        /// </summary>
        [Test]
        public void ItemQueryResultModelConfigurationItemWebhookModelInstalledProductWebhookInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemQueryResultModelConfigurationItemWebhookModelInstalledProductWebhook
            //Assert.IsInstanceOfType<ItemQueryResultModelConfigurationItemWebhookModelInstalledProductWebhook> (instance, "variable 'instance' is a ItemQueryResultModelConfigurationItemWebhookModelInstalledProductWebhook");
        }


        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Test]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }

    }

}
