/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PriceListServiceModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PriceListServiceModelTests
    {
        // TODO uncomment below to declare an instance variable for PriceListServiceModel
        //private PriceListServiceModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PriceListServiceModel
            //instance = new PriceListServiceModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PriceListServiceModel
        /// </summary>
        [Test]
        public void PriceListServiceModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PriceListServiceModel
            //Assert.IsInstanceOfType<PriceListServiceModel> (instance, "variable 'instance' is a PriceListServiceModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CurrencyID'
        /// </summary>
        [Test]
        public void CurrencyIDTest()
        {
            // TODO unit test for the property 'CurrencyID'
        }
        /// <summary>
        /// Test the property 'ServiceID'
        /// </summary>
        [Test]
        public void ServiceIDTest()
        {
            // TODO unit test for the property 'ServiceID'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Test]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'UsesInternalCurrencyPrice'
        /// </summary>
        [Test]
        public void UsesInternalCurrencyPriceTest()
        {
            // TODO unit test for the property 'UsesInternalCurrencyPrice'
        }
        /// <summary>
        /// Test the property 'UserDefinedFields'
        /// </summary>
        [Test]
        public void UserDefinedFieldsTest()
        {
            // TODO unit test for the property 'UserDefinedFields'
        }

    }

}
