/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProductTierModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductTierModelTests
    {
        // TODO uncomment below to declare an instance variable for ProductTierModel
        //private ProductTierModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProductTierModel
            //instance = new ProductTierModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProductTierModel
        /// </summary>
        [Test]
        public void ProductTierModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProductTierModel
            //Assert.IsInstanceOfType<ProductTierModel> (instance, "variable 'instance' is a ProductTierModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ProductID'
        /// </summary>
        [Test]
        public void ProductIDTest()
        {
            // TODO unit test for the property 'ProductID'
        }
        /// <summary>
        /// Test the property 'UnitCost'
        /// </summary>
        [Test]
        public void UnitCostTest()
        {
            // TODO unit test for the property 'UnitCost'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Test]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'UpToUnitCount'
        /// </summary>
        [Test]
        public void UpToUnitCountTest()
        {
            // TODO unit test for the property 'UpToUnitCount'
        }
        /// <summary>
        /// Test the property 'SoapParentPropertyId'
        /// </summary>
        [Test]
        public void SoapParentPropertyIdTest()
        {
            // TODO unit test for the property 'SoapParentPropertyId'
        }
        /// <summary>
        /// Test the property 'UserDefinedFields'
        /// </summary>
        [Test]
        public void UserDefinedFieldsTest()
        {
            // TODO unit test for the property 'UserDefinedFields'
        }

    }

}
