/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QueryActionResultActionTypeModelActionType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QueryActionResultActionTypeModelActionTypeTests
    {
        // TODO uncomment below to declare an instance variable for QueryActionResultActionTypeModelActionType
        //private QueryActionResultActionTypeModelActionType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QueryActionResultActionTypeModelActionType
            //instance = new QueryActionResultActionTypeModelActionType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QueryActionResultActionTypeModelActionType
        /// </summary>
        [Test]
        public void QueryActionResultActionTypeModelActionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QueryActionResultActionTypeModelActionType
            //Assert.IsInstanceOfType<QueryActionResultActionTypeModelActionType> (instance, "variable 'instance' is a QueryActionResultActionTypeModelActionType");
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'PageDetails'
        /// </summary>
        [Test]
        public void PageDetailsTest()
        {
            // TODO unit test for the property 'PageDetails'
        }

    }

}
