/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ResourceRoleDepartmentModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResourceRoleDepartmentModelTests
    {
        // TODO uncomment below to declare an instance variable for ResourceRoleDepartmentModel
        //private ResourceRoleDepartmentModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResourceRoleDepartmentModel
            //instance = new ResourceRoleDepartmentModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResourceRoleDepartmentModel
        /// </summary>
        [Test]
        public void ResourceRoleDepartmentModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResourceRoleDepartmentModel
            //Assert.IsInstanceOfType<ResourceRoleDepartmentModel> (instance, "variable 'instance' is a ResourceRoleDepartmentModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DepartmentID'
        /// </summary>
        [Test]
        public void DepartmentIDTest()
        {
            // TODO unit test for the property 'DepartmentID'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Test]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Test]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }
        /// <summary>
        /// Test the property 'IsDepartmentLead'
        /// </summary>
        [Test]
        public void IsDepartmentLeadTest()
        {
            // TODO unit test for the property 'IsDepartmentLead'
        }
        /// <summary>
        /// Test the property 'ResourceID'
        /// </summary>
        [Test]
        public void ResourceIDTest()
        {
            // TODO unit test for the property 'ResourceID'
        }
        /// <summary>
        /// Test the property 'RoleID'
        /// </summary>
        [Test]
        public void RoleIDTest()
        {
            // TODO unit test for the property 'RoleID'
        }
        /// <summary>
        /// Test the property 'SoapParentPropertyId'
        /// </summary>
        [Test]
        public void SoapParentPropertyIdTest()
        {
            // TODO unit test for the property 'SoapParentPropertyId'
        }
        /// <summary>
        /// Test the property 'UserDefinedFields'
        /// </summary>
        [Test]
        public void UserDefinedFieldsTest()
        {
            // TODO unit test for the property 'UserDefinedFields'
        }

    }

}
