/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ServiceCallTicketModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ServiceCallTicketModelTests
    {
        // TODO uncomment below to declare an instance variable for ServiceCallTicketModel
        //private ServiceCallTicketModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ServiceCallTicketModel
            //instance = new ServiceCallTicketModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServiceCallTicketModel
        /// </summary>
        [Test]
        public void ServiceCallTicketModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ServiceCallTicketModel
            //Assert.IsInstanceOfType<ServiceCallTicketModel> (instance, "variable 'instance' is a ServiceCallTicketModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ServiceCallID'
        /// </summary>
        [Test]
        public void ServiceCallIDTest()
        {
            // TODO unit test for the property 'ServiceCallID'
        }
        /// <summary>
        /// Test the property 'TicketID'
        /// </summary>
        [Test]
        public void TicketIDTest()
        {
            // TODO unit test for the property 'TicketID'
        }
        /// <summary>
        /// Test the property 'SoapParentPropertyId'
        /// </summary>
        [Test]
        public void SoapParentPropertyIdTest()
        {
            // TODO unit test for the property 'SoapParentPropertyId'
        }
        /// <summary>
        /// Test the property 'UserDefinedFields'
        /// </summary>
        [Test]
        public void UserDefinedFieldsTest()
        {
            // TODO unit test for the property 'UserDefinedFields'
        }

    }

}
