/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubscriptionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubscriptionModelTests
    {
        // TODO uncomment below to declare an instance variable for SubscriptionModel
        //private SubscriptionModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubscriptionModel
            //instance = new SubscriptionModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubscriptionModel
        /// </summary>
        [Test]
        public void SubscriptionModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubscriptionModel
            //Assert.IsInstanceOfType<SubscriptionModel> (instance, "variable 'instance' is a SubscriptionModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ConfigurationItemID'
        /// </summary>
        [Test]
        public void ConfigurationItemIDTest()
        {
            // TODO unit test for the property 'ConfigurationItemID'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'EffectiveDate'
        /// </summary>
        [Test]
        public void EffectiveDateTest()
        {
            // TODO unit test for the property 'EffectiveDate'
        }
        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Test]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }
        /// <summary>
        /// Test the property 'ImpersonatorCreatorResourceID'
        /// </summary>
        [Test]
        public void ImpersonatorCreatorResourceIDTest()
        {
            // TODO unit test for the property 'ImpersonatorCreatorResourceID'
        }
        /// <summary>
        /// Test the property 'MaterialCodeID'
        /// </summary>
        [Test]
        public void MaterialCodeIDTest()
        {
            // TODO unit test for the property 'MaterialCodeID'
        }
        /// <summary>
        /// Test the property 'OrganizationalLevelAssociationID'
        /// </summary>
        [Test]
        public void OrganizationalLevelAssociationIDTest()
        {
            // TODO unit test for the property 'OrganizationalLevelAssociationID'
        }
        /// <summary>
        /// Test the property 'PeriodCost'
        /// </summary>
        [Test]
        public void PeriodCostTest()
        {
            // TODO unit test for the property 'PeriodCost'
        }
        /// <summary>
        /// Test the property 'PeriodPrice'
        /// </summary>
        [Test]
        public void PeriodPriceTest()
        {
            // TODO unit test for the property 'PeriodPrice'
        }
        /// <summary>
        /// Test the property 'PeriodType'
        /// </summary>
        [Test]
        public void PeriodTypeTest()
        {
            // TODO unit test for the property 'PeriodType'
        }
        /// <summary>
        /// Test the property 'PurchaseOrderNumber'
        /// </summary>
        [Test]
        public void PurchaseOrderNumberTest()
        {
            // TODO unit test for the property 'PurchaseOrderNumber'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'SubscriptionName'
        /// </summary>
        [Test]
        public void SubscriptionNameTest()
        {
            // TODO unit test for the property 'SubscriptionName'
        }
        /// <summary>
        /// Test the property 'TotalCost'
        /// </summary>
        [Test]
        public void TotalCostTest()
        {
            // TODO unit test for the property 'TotalCost'
        }
        /// <summary>
        /// Test the property 'TotalPrice'
        /// </summary>
        [Test]
        public void TotalPriceTest()
        {
            // TODO unit test for the property 'TotalPrice'
        }
        /// <summary>
        /// Test the property 'VendorID'
        /// </summary>
        [Test]
        public void VendorIDTest()
        {
            // TODO unit test for the property 'VendorID'
        }
        /// <summary>
        /// Test the property 'UserDefinedFields'
        /// </summary>
        [Test]
        public void UserDefinedFieldsTest()
        {
            // TODO unit test for the property 'UserDefinedFields'
        }

    }

}
