/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TicketTagAssociationModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TicketTagAssociationModelTests
    {
        // TODO uncomment below to declare an instance variable for TicketTagAssociationModel
        //private TicketTagAssociationModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TicketTagAssociationModel
            //instance = new TicketTagAssociationModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TicketTagAssociationModel
        /// </summary>
        [Test]
        public void TicketTagAssociationModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TicketTagAssociationModel
            //Assert.IsInstanceOfType<TicketTagAssociationModel> (instance, "variable 'instance' is a TicketTagAssociationModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TagID'
        /// </summary>
        [Test]
        public void TagIDTest()
        {
            // TODO unit test for the property 'TagID'
        }
        /// <summary>
        /// Test the property 'TicketID'
        /// </summary>
        [Test]
        public void TicketIDTest()
        {
            // TODO unit test for the property 'TicketID'
        }
        /// <summary>
        /// Test the property 'SoapParentPropertyId'
        /// </summary>
        [Test]
        public void SoapParentPropertyIdTest()
        {
            // TODO unit test for the property 'SoapParentPropertyId'
        }
        /// <summary>
        /// Test the property 'UserDefinedFields'
        /// </summary>
        [Test]
        public void UserDefinedFieldsTest()
        {
            // TODO unit test for the property 'UserDefinedFields'
        }

    }

}
