/*
 * Datto|Autotask PSA Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;using Object = IO.Swagger.Model.Object;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISubscriptionPeriodsChildApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>QueryActionResultSubscriptionPeriodModelSubscriptionPeriod</returns>
        QueryActionResultSubscriptionPeriodModelSubscriptionPeriod SubscriptionPeriodsChildQuery (long? parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>ApiResponse of QueryActionResultSubscriptionPeriodModelSubscriptionPeriod</returns>
        ApiResponse<QueryActionResultSubscriptionPeriodModelSubscriptionPeriod> SubscriptionPeriodsChildQueryWithHttpInfo (long? parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>EntityInformationResultModel</returns>
        EntityInformationResultModel SubscriptionPeriodsChildQueryEntityInformation (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>ApiResponse of EntityInformationResultModel</returns>
        ApiResponse<EntityInformationResultModel> SubscriptionPeriodsChildQueryEntityInformationWithHttpInfo (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>FieldInformationResultModel</returns>
        FieldInformationResultModel SubscriptionPeriodsChildQueryFieldDefinitions (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>ApiResponse of FieldInformationResultModel</returns>
        ApiResponse<FieldInformationResultModel> SubscriptionPeriodsChildQueryFieldDefinitionsWithHttpInfo (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="id"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod</returns>
        ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod SubscriptionPeriodsChildQueryItem (long? parentId, long? id, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="id"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>ApiResponse of ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod</returns>
        ApiResponse<ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod> SubscriptionPeriodsChildQueryItemWithHttpInfo (long? parentId, long? id, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>UserDefinedFieldInformationResultModel</returns>
        UserDefinedFieldInformationResultModel SubscriptionPeriodsChildQueryUserDefinedFieldDefinitions (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>ApiResponse of UserDefinedFieldInformationResultModel</returns>
        ApiResponse<UserDefinedFieldInformationResultModel> SubscriptionPeriodsChildQueryUserDefinedFieldDefinitionsWithHttpInfo (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of QueryActionResultSubscriptionPeriodModelSubscriptionPeriod</returns>
        System.Threading.Tasks.Task<QueryActionResultSubscriptionPeriodModelSubscriptionPeriod> SubscriptionPeriodsChildQueryAsync (long? parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of ApiResponse (QueryActionResultSubscriptionPeriodModelSubscriptionPeriod)</returns>
        System.Threading.Tasks.Task<ApiResponse<QueryActionResultSubscriptionPeriodModelSubscriptionPeriod>> SubscriptionPeriodsChildQueryAsyncWithHttpInfo (long? parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of EntityInformationResultModel</returns>
        System.Threading.Tasks.Task<EntityInformationResultModel> SubscriptionPeriodsChildQueryEntityInformationAsync (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of ApiResponse (EntityInformationResultModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<EntityInformationResultModel>> SubscriptionPeriodsChildQueryEntityInformationAsyncWithHttpInfo (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of FieldInformationResultModel</returns>
        System.Threading.Tasks.Task<FieldInformationResultModel> SubscriptionPeriodsChildQueryFieldDefinitionsAsync (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of ApiResponse (FieldInformationResultModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<FieldInformationResultModel>> SubscriptionPeriodsChildQueryFieldDefinitionsAsyncWithHttpInfo (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="id"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod</returns>
        System.Threading.Tasks.Task<ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod> SubscriptionPeriodsChildQueryItemAsync (long? parentId, long? id, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="id"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of ApiResponse (ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod)</returns>
        System.Threading.Tasks.Task<ApiResponse<ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod>> SubscriptionPeriodsChildQueryItemAsyncWithHttpInfo (long? parentId, long? id, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);
        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of UserDefinedFieldInformationResultModel</returns>
        System.Threading.Tasks.Task<UserDefinedFieldInformationResultModel> SubscriptionPeriodsChildQueryUserDefinedFieldDefinitionsAsync (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);

        /// <summary>
        ///
        /// </summary>
        /// <remarks>
        ///
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of ApiResponse (UserDefinedFieldInformationResultModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserDefinedFieldInformationResultModel>> SubscriptionPeriodsChildQueryUserDefinedFieldDefinitionsAsyncWithHttpInfo (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SubscriptionPeriodsChildApi : ISubscriptionPeriodsChildApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionPeriodsChildApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SubscriptionPeriodsChildApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionPeriodsChildApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SubscriptionPeriodsChildApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>QueryActionResultSubscriptionPeriodModelSubscriptionPeriod</returns>
        public QueryActionResultSubscriptionPeriodModelSubscriptionPeriod SubscriptionPeriodsChildQuery (long? parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
             ApiResponse<QueryActionResultSubscriptionPeriodModelSubscriptionPeriod> localVarResponse = SubscriptionPeriodsChildQueryWithHttpInfo(parentId, apiIntegrationCode, userName, secret, impersonationResourceId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>ApiResponse of QueryActionResultSubscriptionPeriodModelSubscriptionPeriod</returns>
        public ApiResponse< QueryActionResultSubscriptionPeriodModelSubscriptionPeriod > SubscriptionPeriodsChildQueryWithHttpInfo (long? parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
            // verify the required parameter 'parentId' is set
            if (parentId == null)
                throw new ApiException(400, "Missing required parameter 'parentId' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQuery");
            // verify the required parameter 'apiIntegrationCode' is set
            if (apiIntegrationCode == null)
                throw new ApiException(400, "Missing required parameter 'apiIntegrationCode' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQuery");
            // verify the required parameter 'userName' is set
            if (userName == null)
                throw new ApiException(400, "Missing required parameter 'userName' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQuery");
            // verify the required parameter 'secret' is set
            if (secret == null)
                throw new ApiException(400, "Missing required parameter 'secret' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQuery");

            var localVarPath = "/V1.0/Subscriptions/{parentId}/Periods";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (parentId != null) localVarPathParams.Add("parentId", this.Configuration.ApiClient.ParameterToString(parentId)); // path parameter
            if (apiIntegrationCode != null) localVarHeaderParams.Add("ApiIntegrationCode", this.Configuration.ApiClient.ParameterToString(apiIntegrationCode)); // header parameter
            if (userName != null) localVarHeaderParams.Add("UserName", this.Configuration.ApiClient.ParameterToString(userName)); // header parameter
            if (secret != null) localVarHeaderParams.Add("Secret", this.Configuration.ApiClient.ParameterToString(secret)); // header parameter
            if (impersonationResourceId != null) localVarHeaderParams.Add("ImpersonationResourceId", this.Configuration.ApiClient.ParameterToString(impersonationResourceId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubscriptionPeriodsChildQuery", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<QueryActionResultSubscriptionPeriodModelSubscriptionPeriod>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (QueryActionResultSubscriptionPeriodModelSubscriptionPeriod) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(QueryActionResultSubscriptionPeriodModelSubscriptionPeriod)));
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of QueryActionResultSubscriptionPeriodModelSubscriptionPeriod</returns>
        public async System.Threading.Tasks.Task<QueryActionResultSubscriptionPeriodModelSubscriptionPeriod> SubscriptionPeriodsChildQueryAsync (long? parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
             ApiResponse<QueryActionResultSubscriptionPeriodModelSubscriptionPeriod> localVarResponse = await SubscriptionPeriodsChildQueryAsyncWithHttpInfo(parentId, apiIntegrationCode, userName, secret, impersonationResourceId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of ApiResponse (QueryActionResultSubscriptionPeriodModelSubscriptionPeriod)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<QueryActionResultSubscriptionPeriodModelSubscriptionPeriod>> SubscriptionPeriodsChildQueryAsyncWithHttpInfo (long? parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
            // verify the required parameter 'parentId' is set
            if (parentId == null)
                throw new ApiException(400, "Missing required parameter 'parentId' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQuery");
            // verify the required parameter 'apiIntegrationCode' is set
            if (apiIntegrationCode == null)
                throw new ApiException(400, "Missing required parameter 'apiIntegrationCode' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQuery");
            // verify the required parameter 'userName' is set
            if (userName == null)
                throw new ApiException(400, "Missing required parameter 'userName' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQuery");
            // verify the required parameter 'secret' is set
            if (secret == null)
                throw new ApiException(400, "Missing required parameter 'secret' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQuery");

            var localVarPath = "/V1.0/Subscriptions/{parentId}/Periods";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (parentId != null) localVarPathParams.Add("parentId", this.Configuration.ApiClient.ParameterToString(parentId)); // path parameter
            if (apiIntegrationCode != null) localVarHeaderParams.Add("ApiIntegrationCode", this.Configuration.ApiClient.ParameterToString(apiIntegrationCode)); // header parameter
            if (userName != null) localVarHeaderParams.Add("UserName", this.Configuration.ApiClient.ParameterToString(userName)); // header parameter
            if (secret != null) localVarHeaderParams.Add("Secret", this.Configuration.ApiClient.ParameterToString(secret)); // header parameter
            if (impersonationResourceId != null) localVarHeaderParams.Add("ImpersonationResourceId", this.Configuration.ApiClient.ParameterToString(impersonationResourceId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubscriptionPeriodsChildQuery", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<QueryActionResultSubscriptionPeriodModelSubscriptionPeriod>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (QueryActionResultSubscriptionPeriodModelSubscriptionPeriod) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(QueryActionResultSubscriptionPeriodModelSubscriptionPeriod)));
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>EntityInformationResultModel</returns>
        public EntityInformationResultModel SubscriptionPeriodsChildQueryEntityInformation (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
             ApiResponse<EntityInformationResultModel> localVarResponse = SubscriptionPeriodsChildQueryEntityInformationWithHttpInfo(parentId, apiIntegrationCode, userName, secret, impersonationResourceId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>ApiResponse of EntityInformationResultModel</returns>
        public ApiResponse< EntityInformationResultModel > SubscriptionPeriodsChildQueryEntityInformationWithHttpInfo (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
            // verify the required parameter 'parentId' is set
            if (parentId == null)
                throw new ApiException(400, "Missing required parameter 'parentId' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryEntityInformation");
            // verify the required parameter 'apiIntegrationCode' is set
            if (apiIntegrationCode == null)
                throw new ApiException(400, "Missing required parameter 'apiIntegrationCode' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryEntityInformation");
            // verify the required parameter 'userName' is set
            if (userName == null)
                throw new ApiException(400, "Missing required parameter 'userName' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryEntityInformation");
            // verify the required parameter 'secret' is set
            if (secret == null)
                throw new ApiException(400, "Missing required parameter 'secret' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryEntityInformation");

            var localVarPath = "/V1.0/Subscriptions/{parentId}/Periods/entityInformation";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (parentId != null) localVarPathParams.Add("parentId", this.Configuration.ApiClient.ParameterToString(parentId)); // path parameter
            if (apiIntegrationCode != null) localVarHeaderParams.Add("ApiIntegrationCode", this.Configuration.ApiClient.ParameterToString(apiIntegrationCode)); // header parameter
            if (userName != null) localVarHeaderParams.Add("UserName", this.Configuration.ApiClient.ParameterToString(userName)); // header parameter
            if (secret != null) localVarHeaderParams.Add("Secret", this.Configuration.ApiClient.ParameterToString(secret)); // header parameter
            if (impersonationResourceId != null) localVarHeaderParams.Add("ImpersonationResourceId", this.Configuration.ApiClient.ParameterToString(impersonationResourceId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubscriptionPeriodsChildQueryEntityInformation", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EntityInformationResultModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (EntityInformationResultModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(EntityInformationResultModel)));
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of EntityInformationResultModel</returns>
        public async System.Threading.Tasks.Task<EntityInformationResultModel> SubscriptionPeriodsChildQueryEntityInformationAsync (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
             ApiResponse<EntityInformationResultModel> localVarResponse = await SubscriptionPeriodsChildQueryEntityInformationAsyncWithHttpInfo(parentId, apiIntegrationCode, userName, secret, impersonationResourceId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of ApiResponse (EntityInformationResultModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<EntityInformationResultModel>> SubscriptionPeriodsChildQueryEntityInformationAsyncWithHttpInfo (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
            // verify the required parameter 'parentId' is set
            if (parentId == null)
                throw new ApiException(400, "Missing required parameter 'parentId' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryEntityInformation");
            // verify the required parameter 'apiIntegrationCode' is set
            if (apiIntegrationCode == null)
                throw new ApiException(400, "Missing required parameter 'apiIntegrationCode' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryEntityInformation");
            // verify the required parameter 'userName' is set
            if (userName == null)
                throw new ApiException(400, "Missing required parameter 'userName' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryEntityInformation");
            // verify the required parameter 'secret' is set
            if (secret == null)
                throw new ApiException(400, "Missing required parameter 'secret' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryEntityInformation");

            var localVarPath = "/V1.0/Subscriptions/{parentId}/Periods/entityInformation";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (parentId != null) localVarPathParams.Add("parentId", this.Configuration.ApiClient.ParameterToString(parentId)); // path parameter
            if (apiIntegrationCode != null) localVarHeaderParams.Add("ApiIntegrationCode", this.Configuration.ApiClient.ParameterToString(apiIntegrationCode)); // header parameter
            if (userName != null) localVarHeaderParams.Add("UserName", this.Configuration.ApiClient.ParameterToString(userName)); // header parameter
            if (secret != null) localVarHeaderParams.Add("Secret", this.Configuration.ApiClient.ParameterToString(secret)); // header parameter
            if (impersonationResourceId != null) localVarHeaderParams.Add("ImpersonationResourceId", this.Configuration.ApiClient.ParameterToString(impersonationResourceId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubscriptionPeriodsChildQueryEntityInformation", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EntityInformationResultModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (EntityInformationResultModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(EntityInformationResultModel)));
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>FieldInformationResultModel</returns>
        public FieldInformationResultModel SubscriptionPeriodsChildQueryFieldDefinitions (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
             ApiResponse<FieldInformationResultModel> localVarResponse = SubscriptionPeriodsChildQueryFieldDefinitionsWithHttpInfo(parentId, apiIntegrationCode, userName, secret, impersonationResourceId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>ApiResponse of FieldInformationResultModel</returns>
        public ApiResponse< FieldInformationResultModel > SubscriptionPeriodsChildQueryFieldDefinitionsWithHttpInfo (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
            // verify the required parameter 'parentId' is set
            if (parentId == null)
                throw new ApiException(400, "Missing required parameter 'parentId' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryFieldDefinitions");
            // verify the required parameter 'apiIntegrationCode' is set
            if (apiIntegrationCode == null)
                throw new ApiException(400, "Missing required parameter 'apiIntegrationCode' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryFieldDefinitions");
            // verify the required parameter 'userName' is set
            if (userName == null)
                throw new ApiException(400, "Missing required parameter 'userName' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryFieldDefinitions");
            // verify the required parameter 'secret' is set
            if (secret == null)
                throw new ApiException(400, "Missing required parameter 'secret' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryFieldDefinitions");

            var localVarPath = "/V1.0/Subscriptions/{parentId}/Periods/entityInformation/fields";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (parentId != null) localVarPathParams.Add("parentId", this.Configuration.ApiClient.ParameterToString(parentId)); // path parameter
            if (apiIntegrationCode != null) localVarHeaderParams.Add("ApiIntegrationCode", this.Configuration.ApiClient.ParameterToString(apiIntegrationCode)); // header parameter
            if (userName != null) localVarHeaderParams.Add("UserName", this.Configuration.ApiClient.ParameterToString(userName)); // header parameter
            if (secret != null) localVarHeaderParams.Add("Secret", this.Configuration.ApiClient.ParameterToString(secret)); // header parameter
            if (impersonationResourceId != null) localVarHeaderParams.Add("ImpersonationResourceId", this.Configuration.ApiClient.ParameterToString(impersonationResourceId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubscriptionPeriodsChildQueryFieldDefinitions", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<FieldInformationResultModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (FieldInformationResultModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(FieldInformationResultModel)));
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of FieldInformationResultModel</returns>
        public async System.Threading.Tasks.Task<FieldInformationResultModel> SubscriptionPeriodsChildQueryFieldDefinitionsAsync (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
             ApiResponse<FieldInformationResultModel> localVarResponse = await SubscriptionPeriodsChildQueryFieldDefinitionsAsyncWithHttpInfo(parentId, apiIntegrationCode, userName, secret, impersonationResourceId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of ApiResponse (FieldInformationResultModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<FieldInformationResultModel>> SubscriptionPeriodsChildQueryFieldDefinitionsAsyncWithHttpInfo (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
            // verify the required parameter 'parentId' is set
            if (parentId == null)
                throw new ApiException(400, "Missing required parameter 'parentId' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryFieldDefinitions");
            // verify the required parameter 'apiIntegrationCode' is set
            if (apiIntegrationCode == null)
                throw new ApiException(400, "Missing required parameter 'apiIntegrationCode' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryFieldDefinitions");
            // verify the required parameter 'userName' is set
            if (userName == null)
                throw new ApiException(400, "Missing required parameter 'userName' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryFieldDefinitions");
            // verify the required parameter 'secret' is set
            if (secret == null)
                throw new ApiException(400, "Missing required parameter 'secret' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryFieldDefinitions");

            var localVarPath = "/V1.0/Subscriptions/{parentId}/Periods/entityInformation/fields";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (parentId != null) localVarPathParams.Add("parentId", this.Configuration.ApiClient.ParameterToString(parentId)); // path parameter
            if (apiIntegrationCode != null) localVarHeaderParams.Add("ApiIntegrationCode", this.Configuration.ApiClient.ParameterToString(apiIntegrationCode)); // header parameter
            if (userName != null) localVarHeaderParams.Add("UserName", this.Configuration.ApiClient.ParameterToString(userName)); // header parameter
            if (secret != null) localVarHeaderParams.Add("Secret", this.Configuration.ApiClient.ParameterToString(secret)); // header parameter
            if (impersonationResourceId != null) localVarHeaderParams.Add("ImpersonationResourceId", this.Configuration.ApiClient.ParameterToString(impersonationResourceId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubscriptionPeriodsChildQueryFieldDefinitions", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<FieldInformationResultModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (FieldInformationResultModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(FieldInformationResultModel)));
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="id"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod</returns>
        public ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod SubscriptionPeriodsChildQueryItem (long? parentId, long? id, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
             ApiResponse<ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod> localVarResponse = SubscriptionPeriodsChildQueryItemWithHttpInfo(parentId, id, apiIntegrationCode, userName, secret, impersonationResourceId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="id"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>ApiResponse of ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod</returns>
        public ApiResponse< ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod > SubscriptionPeriodsChildQueryItemWithHttpInfo (long? parentId, long? id, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
            // verify the required parameter 'parentId' is set
            if (parentId == null)
                throw new ApiException(400, "Missing required parameter 'parentId' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryItem");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryItem");
            // verify the required parameter 'apiIntegrationCode' is set
            if (apiIntegrationCode == null)
                throw new ApiException(400, "Missing required parameter 'apiIntegrationCode' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryItem");
            // verify the required parameter 'userName' is set
            if (userName == null)
                throw new ApiException(400, "Missing required parameter 'userName' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryItem");
            // verify the required parameter 'secret' is set
            if (secret == null)
                throw new ApiException(400, "Missing required parameter 'secret' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryItem");

            var localVarPath = "/V1.0/Subscriptions/{parentId}/Periods/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (parentId != null) localVarPathParams.Add("parentId", this.Configuration.ApiClient.ParameterToString(parentId)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (apiIntegrationCode != null) localVarHeaderParams.Add("ApiIntegrationCode", this.Configuration.ApiClient.ParameterToString(apiIntegrationCode)); // header parameter
            if (userName != null) localVarHeaderParams.Add("UserName", this.Configuration.ApiClient.ParameterToString(userName)); // header parameter
            if (secret != null) localVarHeaderParams.Add("Secret", this.Configuration.ApiClient.ParameterToString(secret)); // header parameter
            if (impersonationResourceId != null) localVarHeaderParams.Add("ImpersonationResourceId", this.Configuration.ApiClient.ParameterToString(impersonationResourceId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubscriptionPeriodsChildQueryItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod)));
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="id"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod</returns>
        public async System.Threading.Tasks.Task<ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod> SubscriptionPeriodsChildQueryItemAsync (long? parentId, long? id, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
             ApiResponse<ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod> localVarResponse = await SubscriptionPeriodsChildQueryItemAsyncWithHttpInfo(parentId, id, apiIntegrationCode, userName, secret, impersonationResourceId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="id"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of ApiResponse (ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod>> SubscriptionPeriodsChildQueryItemAsyncWithHttpInfo (long? parentId, long? id, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
            // verify the required parameter 'parentId' is set
            if (parentId == null)
                throw new ApiException(400, "Missing required parameter 'parentId' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryItem");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryItem");
            // verify the required parameter 'apiIntegrationCode' is set
            if (apiIntegrationCode == null)
                throw new ApiException(400, "Missing required parameter 'apiIntegrationCode' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryItem");
            // verify the required parameter 'userName' is set
            if (userName == null)
                throw new ApiException(400, "Missing required parameter 'userName' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryItem");
            // verify the required parameter 'secret' is set
            if (secret == null)
                throw new ApiException(400, "Missing required parameter 'secret' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryItem");

            var localVarPath = "/V1.0/Subscriptions/{parentId}/Periods/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (parentId != null) localVarPathParams.Add("parentId", this.Configuration.ApiClient.ParameterToString(parentId)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (apiIntegrationCode != null) localVarHeaderParams.Add("ApiIntegrationCode", this.Configuration.ApiClient.ParameterToString(apiIntegrationCode)); // header parameter
            if (userName != null) localVarHeaderParams.Add("UserName", this.Configuration.ApiClient.ParameterToString(userName)); // header parameter
            if (secret != null) localVarHeaderParams.Add("Secret", this.Configuration.ApiClient.ParameterToString(secret)); // header parameter
            if (impersonationResourceId != null) localVarHeaderParams.Add("ImpersonationResourceId", this.Configuration.ApiClient.ParameterToString(impersonationResourceId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubscriptionPeriodsChildQueryItem", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ItemQueryResultModelSubscriptionPeriodModelSubscriptionPeriod)));
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>UserDefinedFieldInformationResultModel</returns>
        public UserDefinedFieldInformationResultModel SubscriptionPeriodsChildQueryUserDefinedFieldDefinitions (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
             ApiResponse<UserDefinedFieldInformationResultModel> localVarResponse = SubscriptionPeriodsChildQueryUserDefinedFieldDefinitionsWithHttpInfo(parentId, apiIntegrationCode, userName, secret, impersonationResourceId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>ApiResponse of UserDefinedFieldInformationResultModel</returns>
        public ApiResponse< UserDefinedFieldInformationResultModel > SubscriptionPeriodsChildQueryUserDefinedFieldDefinitionsWithHttpInfo (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
            // verify the required parameter 'parentId' is set
            if (parentId == null)
                throw new ApiException(400, "Missing required parameter 'parentId' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryUserDefinedFieldDefinitions");
            // verify the required parameter 'apiIntegrationCode' is set
            if (apiIntegrationCode == null)
                throw new ApiException(400, "Missing required parameter 'apiIntegrationCode' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryUserDefinedFieldDefinitions");
            // verify the required parameter 'userName' is set
            if (userName == null)
                throw new ApiException(400, "Missing required parameter 'userName' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryUserDefinedFieldDefinitions");
            // verify the required parameter 'secret' is set
            if (secret == null)
                throw new ApiException(400, "Missing required parameter 'secret' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryUserDefinedFieldDefinitions");

            var localVarPath = "/V1.0/Subscriptions/{parentId}/Periods/entityInformation/userDefinedFields";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (parentId != null) localVarPathParams.Add("parentId", this.Configuration.ApiClient.ParameterToString(parentId)); // path parameter
            if (apiIntegrationCode != null) localVarHeaderParams.Add("ApiIntegrationCode", this.Configuration.ApiClient.ParameterToString(apiIntegrationCode)); // header parameter
            if (userName != null) localVarHeaderParams.Add("UserName", this.Configuration.ApiClient.ParameterToString(userName)); // header parameter
            if (secret != null) localVarHeaderParams.Add("Secret", this.Configuration.ApiClient.ParameterToString(secret)); // header parameter
            if (impersonationResourceId != null) localVarHeaderParams.Add("ImpersonationResourceId", this.Configuration.ApiClient.ParameterToString(impersonationResourceId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubscriptionPeriodsChildQueryUserDefinedFieldDefinitions", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<UserDefinedFieldInformationResultModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (UserDefinedFieldInformationResultModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(UserDefinedFieldInformationResultModel)));
        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of UserDefinedFieldInformationResultModel</returns>
        public async System.Threading.Tasks.Task<UserDefinedFieldInformationResultModel> SubscriptionPeriodsChildQueryUserDefinedFieldDefinitionsAsync (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
             ApiResponse<UserDefinedFieldInformationResultModel> localVarResponse = await SubscriptionPeriodsChildQueryUserDefinedFieldDefinitionsAsyncWithHttpInfo(parentId, apiIntegrationCode, userName, secret, impersonationResourceId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="parentId"></param>
        /// <param name="apiIntegrationCode">API Integration Code</param>
        /// <param name="userName">User Name</param>
        /// <param name="secret">Secret</param>
        /// <param name="impersonationResourceId">Impersonation Resource Key (optional)</param>
        /// <returns>Task of ApiResponse (UserDefinedFieldInformationResultModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<UserDefinedFieldInformationResultModel>> SubscriptionPeriodsChildQueryUserDefinedFieldDefinitionsAsyncWithHttpInfo (string parentId, string apiIntegrationCode, string userName, string secret, string impersonationResourceId = null)
        {
            // verify the required parameter 'parentId' is set
            if (parentId == null)
                throw new ApiException(400, "Missing required parameter 'parentId' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryUserDefinedFieldDefinitions");
            // verify the required parameter 'apiIntegrationCode' is set
            if (apiIntegrationCode == null)
                throw new ApiException(400, "Missing required parameter 'apiIntegrationCode' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryUserDefinedFieldDefinitions");
            // verify the required parameter 'userName' is set
            if (userName == null)
                throw new ApiException(400, "Missing required parameter 'userName' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryUserDefinedFieldDefinitions");
            // verify the required parameter 'secret' is set
            if (secret == null)
                throw new ApiException(400, "Missing required parameter 'secret' when calling SubscriptionPeriodsChildApi->SubscriptionPeriodsChildQueryUserDefinedFieldDefinitions");

            var localVarPath = "/V1.0/Subscriptions/{parentId}/Periods/entityInformation/userDefinedFields";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (parentId != null) localVarPathParams.Add("parentId", this.Configuration.ApiClient.ParameterToString(parentId)); // path parameter
            if (apiIntegrationCode != null) localVarHeaderParams.Add("ApiIntegrationCode", this.Configuration.ApiClient.ParameterToString(apiIntegrationCode)); // header parameter
            if (userName != null) localVarHeaderParams.Add("UserName", this.Configuration.ApiClient.ParameterToString(userName)); // header parameter
            if (secret != null) localVarHeaderParams.Add("Secret", this.Configuration.ApiClient.ParameterToString(secret)); // header parameter
            if (impersonationResourceId != null) localVarHeaderParams.Add("ImpersonationResourceId", this.Configuration.ApiClient.ParameterToString(impersonationResourceId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubscriptionPeriodsChildQueryUserDefinedFieldDefinitions", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<UserDefinedFieldInformationResultModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (UserDefinedFieldInformationResultModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(UserDefinedFieldInformationResultModel)));
        }

    }
}
